### ISSUE TITLE
Loading SVG hangs

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-docfx#101]
### Description  
When opening a doc page with a sample, the loading SVG appears to be hanging.

### Steps to reproduce  

1. Open the grid page

### Result  
The loading SVG does not spin.

### Expected result  
The loading SVG should be spinning.

### Attachments  
![untitled](https://user-images.githubusercontent.com/6439482/36091495-9b263276-0fec-11e8-893f-83265918e859.png)

**Comment by zdrawku** [comment]
@tiliev what is the status of this issue? Could you set a severity tag?

**Comment by tiliev** [comment]
@zdrawku The severity is low, but I haven't seen the loading SVG lately, we should check why it's gone.

**Comment by zdrawku** [comment]
Okay, once we finish with the urgent issues for the sprint, we can investigate this.

**Comment by zdrawku** [comment]
As I see this issue is reproducible only with IE and Edge browsers, with Chrome the lag is barely noticeable

**Comment by zdrawku** [comment]
Closing this issue, the loading is good now
