### ISSUE TITLE
Boken links in the Row Selection topic

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-docfx#1039]
1. Go to https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/selection.html#setup
2. Open the rowID and selectionAPI links.

Result:
The rowID does not navigate to the rowID member in the API docs. The selectionAPI link is broken.

**Comment by tachojelev** [comment]
@DiyanDimitrov, the issue seems to be already fixed. Can you confirm, so we can close it?

**Comment by DiyanDimitrov** [comment]
@tachojelev, yes, it is already fixed.
