### ISSUE TITLE
Side Navigation is missing 

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-docfx#104]
**Description**
Side Navigation Menu is missing in Internet Explorer

**Steps to reproduce**
1. Open following link https://www.infragistics.com/products/ignite-ui-angular/angular/components/button.html  in Internet Explorer

**Result**
Side Navigation Menu does not show up.

**Expected result**
Side Navigation Menu must be rendered.

**Attachments**
![image](https://user-images.githubusercontent.com/34240583/36150339-085aee2e-10cc-11e8-8022-c2a28b004e43.png)

**Comment by tiliev** [comment]
Duplicate #185.
