### ISSUE TITLE
Shell strings are all missing

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#105]
1. Go to any page on staging.
2. Check the right side for "IN THIS ARTICLE:".
3. Hover over a code snippet and check for the "COPY" text.

Actual result: None of these appear.  They are all blank.

Expected result: The text from the shell appears.

**Comment by zdrawku** [comment]
Hey Liz, I don't understand what the issue is? Could you please clarify:
![image](https://user-images.githubusercontent.com/11193764/36478903-4aa83b30-170f-11e8-9afa-873c20f4d4db.png)

**Comment by ig-ealbert** [comment]
@zdrawku These are the strings related to #61.  Since that change was committed, they have been missing. Compare with production.
![image](https://user-images.githubusercontent.com/8162597/36485737-c8a7ff0e-16ea-11e8-8890-b7bae7726b8a.png)

**Comment by ig-ealbert** [comment]
@zdrawku It seems to be caused by this error: docfx.vendor.js:4 GET https://staging.infragistics.local/angularsite/resources-en.json 404 (Not Found)

**Comment by ig-ealbert** [comment]
@kdinev @zdrawku This is public now.  I get the same error on production, and the shell strings are missing. :(

**Comment by zdrawku** [comment]
Hey Liz, we are going to take care of this as soon as possible

**Comment by zdrawku** [comment]
Thanks to ES team this issue has been fixed.

**Comment by ig-ealbert** [comment]
I see this issue again now that the build is working.
Same error in the console about the missing file.
https://jp.staging.infragistics.local/angularsite/components/grid.html

**Comment by ig-ealbert** [comment]
The configuration issue was fixed by Anastas today.  The strings appear now for both EN and JP on staging, and would be on production once published.
