### ISSUE TITLE
Improve StackBlitz integration docs

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-docfx#1053]
Improve the StackBlitz integration docs. Please describe how can you add StackBlitz button without having a sample in an iframe.

**Comment by zdrawku** [comment]
Section available [here](https://github.com/IgniteUI/igniteui-docfx/blob/master/.github/CONTRIBUTING.md#code-view-configuration)

Using of [explicit editor](https://github.com/IgniteUI/igniteui-docfx/blob/master/README.md#using-explicit-editor-for-live-editing-samples) property
