### ISSUE TITLE
Stackblitz button is disabled

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-docfx#1097]
1. Build the documentation from the ysugiura/0228 branch.
2. Open the date picker topic.
3. Check the "Date Picker with a custom formatter" and the "Default Date Picker" samples.

The Stackblitz buttons are disabled.
This is happening if you build the documentation from the master branch as well.

**Comment by zdrawku** [comment]
This is because the samples were built with `npm run start`. In order to run the samples with the live-editing configurations we need to use [`npm run start:live-editing`](https://github.com/IgniteUI/igniteui-angular-samples#dev-server-and-live-editing)
