### ISSUE TITLE
StackBlitz button under sample is grayed out in Axis sample

### ISSUE THREAD

**Issue by yoshimis** [IgniteUI/igniteui-docfx#1201]
### Description  
StackBlitz button under sample is grayed out.

### Steps to reproduce  

1. Open https://www.infragistics.com//angularsite/components/datachart_axis_types.html

or 

JP and KR versions:
 https://jp.infragistics.com//angularsite/components/datachart_axis_types.html
 https://kr.infragistics.com//angularsite/components/datachart_axis_types.html

### Result  
StackBlitz button under sample is grayed out.

### Expected result  
StackBlitz button should be enabled or remove the button if StackBlitz is not working.

**Comment by HUSSAR-mtrela** [comment]
this issue is already fixed
