### ISSUE TITLE
Doughnut chart's Legend demo doesn't work

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-docfx#1214]
1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/doughnutchart.html
2. Scroll down to Legend Demo
3. Examine the demo

Actual results:
The demo is not shown.

Expected results:
The demo should be shown.

**Comment by zdrawku** [comment]
Error is thrown "ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'charts/doughnut-chart-legend'
Error: Cannot match any routes. URL Segment: 'charts/doughnut-chart-legend'" 

The URL itself can be wrong.

**Comment by HUSSAR-mtrela** [comment]
this issue is a duplicate of issue #1135
