### ISSUE TITLE
GitHub alert with high sevirity caused by Axios security issue 

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx#1260]
After further investigation, it looks like the issue has been reported (axios/axios#1098) in the axios repo and [a fix has been merged](https://github.com/axios/axios/commit/0d4fca085b9b44e110f4c5a3dd7384c31abaf756#diff-13c4730a3365dedb3437af189b18e6a9R219) to master.

For now, we need to wait for it to be released and then adjust our dependency if needed.

**Comment by devaKumaraswamy** [comment]
Is there a test version released to try? Cheers...

**Comment by jlandrum** [comment]
@devaKumaraswamy `0.19.0-beta.1` is currently available on NPM and features the fix. It may have other breaking changes though.

**Comment by zdrawku** [comment]
Fixed with axios-0.19.0
