### ISSUE TITLE
Change links, that refer to bookmarks, which differ from their bookmarks text.

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-docfx#1276]
During build igniteui-docfx in KR or JP version, there are multiple warnings that indicate wrong links. These links are not referencing outer sources, but inner bookmarks:

![avalc](https://user-images.githubusercontent.com/25771040/59041990-4ff39400-8882-11e9-8d1b-da48120ed84c.PNG).

The problem here is that there is no such bookmark with text **available-commands**(probably it is translated in KR/JP) and docfx warns that the link references nothing. These are the warnings in the KR and JP versions, respectfully:

![KRversionBuild](https://user-images.githubusercontent.com/25771040/59042221-ba0c3900-8882-11e9-8282-23a22e7a7db2.PNG)

![JPBuild](https://user-images.githubusercontent.com/25771040/59042238-c1334700-8882-11e9-8836-6a775ace2c0a.PNG)

The fix is to change the _link_ **([ **text** ] ( _link_.md ))** to be equal to the bookmark it is referencing.

Related to: #1259

**Comment by damyanpetev** [comment]
@zdrawku @Lipata 
I think this should not be an issue w/ the Japanese docs - that'd mean localized docs would need to translate anchor inside links as well. That seems a bit much.

Sadly, I don't think DocFX flavor of markdown has solved this issue as I can't seem to find anything in their docs. And the MS docs guide ref the good old tag-in-header tactic we used to employ for older Ignite UI docs: https://docs.microsoft.com/en-us/contribute/markdown-reference#explicit-anchor-links
At least DocFX picks that anchor tag id for the side ToC it generates..

Could restrict the use of anchor links (which is lame TBH) and/or add those manually in places where we need them.. or mass update the docs. Dunno.

**Comment by damyanpetev** [comment]
Also I quite like the AsciiDoc way of doing those, but not sure if that can be done w/ a plugin: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#section-titles (see "Explicit id")

**Comment by zdrawku** [comment]
Thank you for your comments, Damyan!
