### ISSUE TITLE
Broken link for IgxCarouselModule in Carousel Component doc

### ISSUE THREAD

**Issue by DaizenIG** [IgniteUI/igniteui-docfx#1310]
Url containing issues:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/carousel.html
https://jp.infragistics.com/products/ignite-ui-angular/angular/components/carousel.html

Symptom:
the link to IgxCarouselModule in Usage section return 404
"The carousel can be used as a full-screen element or situated inside another component. Also, the slides may feature any valid html content inside, including other Angular components. To get started with the Ignite UI for Angular Carousel, let's first import the **_IgxCarouselModule_** in our app.module.ts file:"

Expected Result:
link should be valid.

**Comment by mmart1n** [comment]
This issue has already been resolved.
