### ISSUE TITLE
Broken link for IgxProgressBarModule in Circular Progressbar component doc

### ISSUE THREAD

**Issue by DaizenIG** [IgniteUI/igniteui-docfx#1311]
Step to reproduce:
issues can be observed:
EN - https://www.infragistics.com/products/ignite-ui-angular/angular/components/circular_progress.html
JP - https://www.infragistics.com/products/ignite-ui-angular/angular/components/circular_progress.html

a link in Usage section returns 404:
_"Circular Progress Indicator can be used to show a user that he is in a process. To get started with the Ignite UI for Angular Circular Progress, we should first import the **IgxProgressBarModule** in the app.module.ts file:"_

**Comment by mmart1n** [comment]
This issue has already been resolved.
