### ISSUE TITLE
Add Styling examples for PwnJS components

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-docfx#1340]
We should add some samples that showcase how users can customize our components and make full use of the theming engine:
- [x] Overlay
    - [x] Add styling section to topic that explains theme scoping when using overlay
    - [x] Add side-by-side comparison sample - two drop-downs, both under same `<div>`, theme applied only to one of them (one should have `overlay.outlet` set to `component.host` 
- [x] [Expansion Panel](https://www.infragistics.com/products/ignite-ui-angular/docs/sass/latest/index.html#function-igx-expansion-panel-theme)
    - Styling of the header text, icon color and borders is available through the expansion panel's theme. A good example would be showing another one of our component inside of the panel and showcasing how the theme applies **ONLY** to the expansion panel
- [x] [Banner](https://www.infragistics.com/products/ignite-ui-angular/docs/sass/latest/index.html#function-igx-banner-theme)
    - Style the banner of an application to be contrast colors of the app so it is more visible?
- [x] [Checkbox](https://www.infragistics.com/products/ignite-ui-angular/docs/sass/latest/index.html#function-igx-checkbox-theme)
    - Style the checkbox of an application to be contrast colors of the app so it is more visible?
- [x] [Drop-down](https://www.infragistics.com/products/ignite-ui-angular/docs/sass/latest/index.html#function-igx-drop-down-theme)
   - [x] Add example where drop-down is styled with theme engine. The sample should show how the `igx-drop-down-theme` affects **all** of the following: `igx-drop-down`, `igx-combo`, `igx-select` (side-by-side comparison)
   - [x] Add sample where drop-down, select and combo are all style **independently** (side-by-side comparison). Use this sample across all 3 topics.
   - [x] Add styling section to `igx-drop-down` topic, explaining how the drop-down theme is used and what it affects (1st sample) and how it can be scoped to properly affect only a specific component (2nd sample). Link to overlay styling section.
    - **Consideration** Something that a lot of users could try to do is an odd-even item styling. This can be done with `even/odd` properties exposed by `*ngFor` or by calculating based on the index (also applicable through `igxForOf`). This **DOES NOT** necessarily require the use of the theming engine - the user has full control over the content of the drop-down-item and can define their styles in normal css classes
- [x] [Combo](https://www.infragistics.com/products/ignite-ui-angular/docs/sass/latest/index.html#function-igx-combo-theme)
    - [x] Add section to igx-combo topic explaining how the `igx-drop-down-theme` in conjustion with [input-group](https://www.infragistics.com/products/ignite-ui-angular/docs/sass/latest/index.html#function-igx-input-group-theme) and [button](https://www.infragistics.com/products/ignite-ui-angular/docs/sass/latest/index.html#function-igx-button-theme) themes can be used to style the combo. Use combined sample and add link to `igx-drop-down` styling section for more details
- [x] **Select**
    - [x] Add section to igx-select topic explaining how the `igx-drop-down-theme` in conjustion with [input-group](https://www.infragistics.com/products/ignite-ui-angular/docs/sass/latest/index.html#function-igx-input-group-theme) theme can be used to style the combo. Use combined sample and add link to `igx-drop-down` styling section for more details

**Comment by IvayloG** [comment]
Related https://github.com/IgniteUI/igniteui-angular-samples/pull/1276

**Comment by ViktorSlavov** [comment]
Master issue:
https://github.com/IgniteUI/igniteui-docfx/issues/1275
