### ISSUE TITLE
Grid CRUD documentation - incomplete and misleading

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-docfx#1352]
The current section on [editing](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/editing.html) in the grids is both incomplete and misleading.

Main pain points:
- No mention of custom editor templates. There is some information [here](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html#columns-configuration) but it tricks the user into binding to the wrong property of the template context.
- No mention of available CRUD events, when they are thrown and sample usage with them.
- What is the difference between providing a default cell template and an editor cell template.

**Comment by Lipata** [comment]
Update existing editing topic by adding a CRUD events selections after CRUD operations. More snippets defined in the topic for 1 and 3 in the issue. 

Update Main Demo:
 - Fix cell edit template binding
 - Make combo not a box type 
 - Combo full width 

New Demo with edit events 
 - Prevent end edit when validation error. Both invalid editor state and unable to exit edit mode. 
 - On successful update – toast with "value changed for cell X"  w/ comment in code to handle change there
