### ISSUE TITLE
Broken links in Batch editing template

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx#1420]
1. Open [Grid ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/batch_editing.html)or [HierarchicalGrid ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/batch_editing.html)batch editing topic.
2. Select "igxBaseTransaction, igxTransaction and igxHierarchical transaction explained" hyperlink from the first sentence.
3. 404 error is returned on [transaction-how-to](https://www.infragistics.com/products/ignite-ui-angular/angular/components/transaction-how-to.md)

**Comment by Lipata** [comment]
fixed with #1411
