### ISSUE TITLE
IgxDataChartModule not found

### ISSUE THREAD

**Issue by zhangchenyue** [IgniteUI/igniteui-docfx#1508]
copy the code from demo
import { IgxDataChartModule } from 'igniteui-angular-charts/ES5/igx-data-chart-module';
the 'igniteui-angular-charts/ES5/igx-data-chart-module'  is not exist

**Comment by kdinev** [comment]
@HUSSAR-mtrela Should I close the issue?

**Comment by HUSSAR-mtrela** [comment]
closing because docs are updated to use new syntax for loading modules:

import { IgxDataChartModule } from 'igniteui-angular-charts'
