### ISSUE TITLE
Enhance the demo's layout

### ISSUE THREAD

**Issue by sbozalieva** [IgniteUI/igniteui-docfx#152]
- Differentiate the demo from the rest of the article. 
- Add the StackBlitz button as part of it.

Similar to the treatment of the demos here:
https://material.angular.io/components/slider/overview

**Comment by SlavUI** [comment]
To be honest I don't like this approach :) but of course I'm open to suggestions

**Comment by sbozalieva** [comment]
@SlavUI Can you elaborate on what is it exactly that you don't like?:)

**Comment by SlavUI** [comment]
@sbozalieva I don't like the way the demos are presented on the material page I prefer the was we are showing them right now. I don't like the gray box that separates the Demo from the Story as well as the positioning of the Stackblitz link and the Source Code icon. They don't seem very user friendly to me :) If you mean the Tabs on top the separate Overview, API and Examples that you can disregard my comments :)

**Comment by zdrawku** [comment]
@sbozalieva, do we have any updates on this? @SlavUI should we take some action or close the issue?

**Comment by SlavUI** [comment]
I'm closing this one as for me current Demo Vision is really good. We can open a new request after Milestone 3 is completed

**Comment by sbozalieva** [comment]
Reopened after discussion with @kdinev
