### ISSUE TITLE
There is no information about accessibility compliance in the documentation

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-docfx#1537]
According to the grid spec we're conforming to the[ WAI-ARIA specification](https://github.com/IgniteUI/igniteui-angular/wiki/igxGrid-Specification#aria-support). This is not described in the documentation.

My suggestion is to add a dedicated topic about accessibility compliance, or add an "Accessibility Compliance" section in the topics where applicable.

**Comment by zdrawku** [comment]
We've added such [section ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/framework-and-features/framework-and-features.html#accessibility-and-directionality)and I hope soon we will expand it even more
