### ISSUE TITLE
Map - Incorrect import statement in docs

### ISSUE THREAD

**Issue by brianlagunas** [IgniteUI/igniteui-docfx#1558]
The Map topic has the wrong import statement on it. 

It has:
`import { IgxGeographicMapModule } from "igniteui-angular-maps/ES5/igx-map-module";`

When it should be: 
`import { IgxGeographicMapModule } from 'igniteui-angular-maps/ES5/igx-geographic-map-module';`

https://www.infragistics.com/products/ignite-ui-angular/angular/components/map_overview.html#required-modules

**Comment by zdrawku** [comment]
Thank you, Brian for letting us know about that. As the [Data Visualization changes are made from the Internal docfx repository](https://github.com/IgniteUI/igniteui-docfx/blob/master/.github/CONTRIBUTING.md#updating-of-data-visualization-related-topics), I am going to mention @HUSSAR-mtrela and @pamelabrasil as this issue will be fixed there.

**Comment by HUSSAR-mtrela** [comment]
already fixed
