### ISSUE TITLE
Button documentation on official website is not full

### ISSUE THREAD

**Issue by TopchetoEU** [IgniteUI/igniteui-docfx#1656]
Right now I am developing a new angular app. I tried to use IgniteUI button, so I looked up the documentation, followed all the steps and it worked, until I reached the part with adding ripples. The documentation told me just to add "igxRipple" directive in the button tag but didn't told me to add IgxRippleModule to app.module.ts imports.

**Comment by zdrawku** [comment]
Hello @TopchetoEU I see where you are coming from, we do not mention this in [the section where we refer to the igxRipple](https://www.infragistics.com/products/ignite-ui-angular/angular/components/button.html#usage). We mention it only in the [Ripple's topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/ripple.html#dependencies) This will be updated accordingly.
