### ISSUE TITLE
Images are broken in tabbar sample

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#17]
1. Go here:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/tabbar.html
2. Observe images in the running sample on the left.

Actual result:
The images are all broken.

Expected result:
They should appear.

**Comment by simeonoff** [comment]
Fixed in https://github.com/IgniteUI/igniteui-angular-samples/pull/32
