### ISSUE TITLE
Broken link in transaction topic

### ISSUE THREAD

**Issue by yoshimis** [IgniteUI/igniteui-docfx#1727]
1. Open https://staging.infragistics.com/products/ignite-ui-angular/angular/components/transaction.html
2. Scroll down to the bottom and click "[Building a transaction service for managing large scale editing experiences](https://blog.angular.io/building-a-transaction-service-for-managing-large-scale-editing-experiences-ded666eafd5e)" blog

Result: 500

**Comment by dafo** [comment]
@yoshimis can you please confirm you are still able to reproduce this issue?
I tested both links - the one in the last sentence of the topic and the one inside the "Additional Resources" section and they correctly navigate to the desired blog post - https://blog.angular.io/building-a-transaction-service-for-managing-large-scale-editing-experiences-ded666eafd5e

**Comment by yoshimis** [comment]
It was caused by the add-blocker.
