### ISSUE TITLE
Create separate documentation topics for the pre-built themes

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-docfx#1774]
Create separate topics for
- [x] Material theme (light and dark)
- [x] Fluent theme (light and dark, word and excel inspired)
- [x] Bootstrap theme (light and dark)
- [x] Review the [Global Themes topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/global-theme.html#switching-from-material-to-fluent-theme) and remove redundant content
- [x] Insert the topics in the ToC between Global Themes and Component Themes and add a new tag
- [x] Review the [Theming Examples topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/examples.html)

**Comment by StefanIvanov** [comment]
@desig9stein have you reviewed the Theming Examples topic as well and do we need to make any updates / changes to it?

**Comment by desig9stein** [comment]
@StefanIvanov yes we should do some refactoring there as well, but let's create a separate issue for this.

**Comment by StefanIvanov** [comment]
ОК I have created [#1826](https://github.com/IgniteUI/igniteui-angular-samples/issues/1826)

**Comment by StefanIvanov** [comment]
Closed with #1782
