### ISSUE TITLE
ThemingWidget does not apply any themes to the scrollbar

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-docfx#1783]
When choosing a new theme from the Theming Widget, the scrollbar is not affected and stay in contrast to all other elements in the grid.

Scrollbar should be affected by the theme applied and match the rest of the grid UI elements.

Related to https://github.com/IgniteUI/igniteui-angular/issues/6675

**Comment by dkamburov** [comment]
@radomirchev According to Simo this is for the Design Team
