### ISSUE TITLE
Themes page does not discuss component theming

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#180]
1. Go here:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes.html

2. Search for "We'll take a deeper look at what `$exclude` does later on when we talk about individual component themes.".

This component themes section does not exist.  So we never explain `$exclude`.

**Comment by SlavUI** [comment]
@ig-ealbert please have in mind that we are currently developing the documents for each document. We will be updating this during the week.

**Comment by zdrawku** [comment]
@desig9stein, do we have any updates on this? Could you please add tags for the issue, like severity for example. If we are not planning to add individual component themes section soon, just let us know.

**Comment by simeonoff** [comment]
@zdrawku I am closing this. There are now topics discussing component themes.
