### ISSUE TITLE
[JP] There is a section that is not translated into Japanese

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-docfx#1805]
1. Go to https://jp.infragistics.com/products/ignite-ui-angular/angular/components/grid/state_persistence.html
2. Observe there is a section that is not translated into Japanese.
--> Please translate it into Japanese.

![image](https://user-images.githubusercontent.com/14340675/75520881-e20f7e00-5a49-11ea-94e1-ba7999d6540c.png)

**Comment by randriova** [comment]
Closing the bug, as currently localization is not possible since the text is part of the sample.
