### ISSUE TITLE
Left side Menu is not visible under IE11, errors in the console

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx#185]
1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html

Result:
Menu on the left is missing

![image](https://user-images.githubusercontent.com/11193764/36800843-2843fbb0-1cb9-11e8-91fc-f7ceb01369bc.png)

**Comment by kdinev** [comment]
This is caused by the `copyCode` function being marked as `async`.
