### ISSUE TITLE
DataGrid, Country flags don't match the country name

### ISSUE THREAD

**Issue by MikeTechSpeak** [IgniteUI/igniteui-docfx#19]
I only know a few off hand, while some are correct. There are a number that are wrong:
The United Kingdom has the USA flag
USA has the Uruguay flag
UAE has the USA flag
Tanzania has Thailand flag

**Comment by zdrawku** [comment]
Close after merge of pull request https://github.com/IgniteUI/igniteui-angular-samples/pull/28
