### ISSUE TITLE
[igxFocus] and [igxTextSelection] documentation

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx#1907]
Create/update a topic to cover both directives:
- igxFocus - The directive allows you to force focus for every element it is applied
- igxTextSelection - The directive allows you to select the whole text range for every element with text content it is applied.

**Comment by Lipata** [comment]
Use those new topics as a reference in topics for igxInput, igxMask, where their usage is a common scenario.
