### ISSUE TITLE
[igx-paginator] missing pageChange and perPageChange documentation

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-docfx#1909]
`page` and `perPage` are two way binded input properties of the grid and therefore there are `pageChange` and `perPageChange` event emitters available. This is not documented sufficiently neither in the pagination topic nor in the API documentation. 

Related to: https://github.com/IgniteUI/igniteui-angular/issues/7215#issuecomment-620528449

**Comment by zdrawku** [comment]
Done
