### ISSUE TITLE
wrong import for dock manager

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-docfx#1953]
Instead of:
import { defineCustomElements } from "@infragistics/igniteui-dockmanager/loader";

update the snippet with:
import { defineCustomElements } from 'igniteui-dockmanager/loader';

![Screenshot 2020-05-20 at 15 18 09](https://user-images.githubusercontent.com/7037740/82445276-2fc9de80-9aad-11ea-908c-b0cc82cb4971.png)

**Comment by zdrawku** [comment]
Fixed https://www.infragistics.com/products/ignite-ui-angular/angular/components/dock-manager.html
