### ISSUE TITLE
selectLabel is not working in grid Paging

### ISSUE THREAD

**Issue by jaya0selva** [IgniteUI/igniteui-docfx#2055]
## Description  
Describe the issue.
selectLabel Property is not working in demo also.
https://stackblitz.com/angular/nkknxdjjblr
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/paging.html

 * igniteui-angular version: 10.0.1
 * browser: chrome

## Steps to reproduce  

![image](https://user-images.githubusercontent.com/40403770/86244369-7b4fcc00-bbc5-11ea-8d85-a3f2f259f72a.png)

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by jaya0selva** [comment]
can you provide an example for this
https://stackblitz.com/angular/eyvpxgmxxov

Can you provide exact replacement for this line in HTML

[selectLabel]="'Records per page:'"

**Comment by wnvko** [comment]
@jaya0selva 
Stackblitz has some issue now, so [here](https://codesandbox.io/s/aged-fire-ms7mh?file=/src/app/grid/grid-pager-sample/grid-pager-sample.component.ts) is shown how to change the resource string of `IgxPaginatorComponent`.

**Comment by jaya0selva** [comment]
@wnvko 

It works. But the change is applied to all the grid in the page.

![image](https://user-images.githubusercontent.com/40403770/86711369-837e9000-c039-11ea-8018-158036280243.png)

We were showing the total records count in 'selectLabel' dynamically for each grid in the page. 

Can you please share the replacement for it.

**Comment by zdrawku** [comment]
Thank you @jaya0selva, we've added a [Localization section](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/paging.html#localization) under our Paging topic with a live-sample. I hope you will find it informative and helpful.
Note: Use the CodeSandbox live-demo, it looks like we are having some problems with StackBlitz that are still under investigation.
