### ISSUE TITLE
JP doc: rowData property is presented in Ignite UI for Angular 9.x API Reference

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-docfx#2092]
`rowData` property is newly added in Ignite UI for Angular 10([reference](https://github.com/IgniteUI/igniteui-angular/issues/7833)). However, on JP doc, 9.1.7 version of API reference presents it. Would you remove it on 9 version of the JP API refenrece? On EN doc, it is not presented on 9 version.

https://jp.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/igridediteventargs.html#rowdata
![image](https://user-images.githubusercontent.com/14340675/88035393-07c62c80-cb7d-11ea-8183-9f95ec52f066.png)

**Comment by zdrawku** [comment]
@randriova this might be outdated

**Comment by randriova** [comment]
@zdrawku This has already been fixed in 9.1.22 from what I see.

![image](https://user-images.githubusercontent.com/54146583/97854339-fc4cda80-1d01-11eb-8572-6ded37158382.png)
