### ISSUE TITLE
Material icons extended sample

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-docfx#2224]
Material icons extended sample loads samples home page.

### Steps to reproduce:
1. Go to [Material Icons Sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/material_icons_extended.html).
2. Check the sample.

**Comment by simeonoff** [comment]
@wnvko Does this problem still persist?

**Comment by wnvko** [comment]
Nope, I am closing this issue.
