### ISSUE TITLE
Alphabetize the TOC items under Angular Grid

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-docfx#2319]
Items in Angular Samples TOC are not alphabetically sorted:
![image](https://user-images.githubusercontent.com/52001020/96463567-850e4580-122f-11eb-92f9-13652ac050b5.png)

To improve the user experience the items under Angular Data/Hierarchical and Tree Grid in TOC have to be alphabetically sorted.

**Comment by zdrawku** [comment]
@dobromirts, we should do that for nested TOC items, not only for the Grid
