### ISSUE TITLE
Update of components description

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-docfx#2460]
All public components' [descriptions](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html) should be revised and updated if needed.

Issue is created to replace: [6104](https://github.com/IgniteUI/igniteui-angular/issues/6104)

**Comment by kdinev** [comment]
Closing this as a non-docfx issue. The descriptions are applicable to typedoc and any work related to those should be tracked as part of `igniteui-angular`.
