### ISSUE TITLE
Button group topic is not navigated to its position in the TOC when clicked

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx#2479]
1. Open the [Angular documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid).
2. Find the [Button group](https://www.infragistics.com/products/ignite-ui-angular/angular/components/tabbar) topic BUT while scrolling through the TOC, not searching it
3. Click on the TOC item.

After page refresh, the position in the toc is at the top, not at the Button group topic position.

**Comment by HristoP96** [comment]
This is a a redirect problem which can be fixed with the renaming of the topic MD file or removing the redirect rule from the global web config

**Comment by zdrawku** [comment]
In my opinion we should remove the redirect rule from the globa config, which can be [found here](http://tfs.infragistics.local:8080/tfs/Engineering/WebProperties/Web%20Team/_versionControl?path=%24%2FWebProperties%2FDEV%2FUmbraco%2FU7.3%2FInfragistics.Web.Umbraco.Extensions%2Fconfig%2FUrlRewriting.config&_a=contents)
