### ISSUE TITLE
Change frame height and excel fileName code snippet.

### ISSUE THREAD

**Issue by onlyexeption** [IgniteUI/igniteui-docfx#2590]
### Steps to reproduce:
1. Go to https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/toolbar#features
2. Click either the pin or hide button.

### Actual:
The frame is too short and it doesn't fit all values.

### Expected:
For convenience, it should display all values without them being cut.

![image](https://user-images.githubusercontent.com/19392175/108368144-cb39dc80-7202-11eb-968a-24f8c3dea507.png)

### Steps to reproduce:
1. Go to https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/toolbar#data-exporting
2. Export a file

### Actual:
The fileName in the code snippet is set to ``options.fileName = `Report_${new Date().toDateString()}`;`` but in reality it exports as Custom Name

### Expected:
The snippet and actual code should be consistent

**Comment by zdrawku** [comment]
I am removing this item from the sprint, we have other priorities to focus on and probably will get back to it some of the upcoming iterations
