### ISSUE TITLE
Improve Extended Material Icons topic for SEO

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-docfx#2625]
Following research on how to improve the visibility of the topic for search engines, we should amend the changes proposed [here](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/Ed0lfR6WNupGkiJGRViwc7EBBWDtda7CImId3Dqbc8cIxw?e=aJUfwv) and add the keywords as per the list [here](https://infragisticsinc297.sharepoint.com/:x:/g/Groups/marketing/EVJ8m08m50FDqfWjM0vPZrYBe5oQmZ-WJylZAIWn6cJ_CA?e=LANNZl)

**Comment by aatanasov2** [comment]
@StefanIvanov @simeonoff  can you review the copy 

https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EXEc_9ptFZNFjXV9isXotiUBXji99dauUjtDaAKWrZYSmA?e=4JXIXK
There are some comments in the document, where we need your input.

**Comment by StefanIvanov** [comment]
Thanks @aatanasov2 we are looking at it right now and leaving comments

**Comment by morbidiam** [comment]
thanks for the comments. i will edit and rewrite the text and will send the file for a final review.

**Comment by morbidiam** [comment]
here's the updated version. please review it when you have the time @StefanIvanov  @aatanasov2 @simeonoff

**Comment by StefanIvanov** [comment]
@morbidiam it looks good to me

**Comment by aatanasov2** [comment]
@StefanIvanov  @simeonoff  If all OK, let's schedule the copy for publishing

**Comment by StefanIvanov** [comment]
@aatanasov2 as far as I remember our agreement was that once you drafted things for us, we would be making the changes, so I will leave it to @simeonoff to assign someone to go ahead with this :)
