### ISSUE TITLE
Add CTA banners

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx#2637]
The CTA banners are ready and should be added to the desired topics. @dobromirts when the task in slingshot is ready you will be assigned there.

**Comment by aatanasov2** [comment]
@zdrawku https://infragisticsinc297.sharepoint.com/Groups/marketing/Website/Forms/AllItems.aspx?id=%2FGroups%2Fmarketing%2FWebsite%2FDoc%20FX%20CTA%20banners&p=true&originalPath=aHR0cHM6Ly9pbmZyYWdpc3RpY3NpbmMyOTcuc2hhcmVwb2ludC5jb20vOmY6L2cvR3JvdXBzL21hcmtldGluZy9FazZlY0ZFdEVncERrZU1tSU1RdF9JOEJTUWpQa2pBdHdOUWJBNGxlYXRRQVpRP3J0aW1lPUpZZzlFbDdsMkVn
