### ISSUE TITLE
There are no financial chart images

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#268]
In the financial chart topic, there are images referenced. However, these images do not exist in the images folder.

**Comment by ig-ealbert** [comment]
This doesn't address the issue.  There are no images for the financial chart in the images folder.

**Comment by ig-ealbert** [comment]
@pamelabrasil I see that you added these images in #270 but you also removed them from the table.  The table is still expecting 3 columns (according to the headers in the .md) so was that intentional?

**Comment by pamelabrasil** [comment]
I decided to remove the images, the table should be fixed now

**Comment by ig-ealbert** [comment]
Images were removed from the topic but were still added to the images folder.  Well, I guess that's for future use?  Not a "visible" problem anymore.

**Comment by ig-ealbert** [comment]
The table issue was fixed in #280.
