### ISSUE TITLE
Update Theme Topics for a deprecated property of the igxGridToolbar Component

### ISSUE THREAD

**Issue by viktorkombov** [IgniteUI/igniteui-docfx#2681]
With the release of the 11.0 version of Ignite UI for Angular the property “columnHidingUi” of the IgxGridToolbarComponent has been deprecated. However, it is still mentioned in the following topics::
[Grid Column Hiding](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/column-hiding)
[Tree Grid Column Hiding](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/column-hiding)
[Hierarchical Grid Column Hiding
](https://www.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/column-hiding)

**Comment by ChronosSF** [comment]
This is best done by @zdrawku's team as they refactored the toolbar and will provide better alternative docs in those topics.
