### ISSUE TITLE
Clarification of Dock Manager with Data Analysis

### ISSUE THREAD

**Issue by KaushikEDS** [IgniteUI/igniteui-docfx#2755]
## Question  
I have an issue with the documentation of Dock Manager Data Analysis.
*https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/data-analysis*
I get that I'm supposed to use Igx Grid & Igx Extras but from the documentation, it's very unclear how to develop the code.
I want the source code for *https://www.infragistics.com/angular-demos-lob/grid-dynamic-chart-data/data-analysis-dock-manager* as the Data analysis page doesn't clarify implementation with Dock Manager.
It's kinda hard to implement anything by looking at the documentation.

 * igniteui-angular version: "@infragistics/igniteui-angular": "^11.1.8"
 * browser: Chrome

**Comment by zdrawku** [comment]
Hey @KaushikEDS, thank you for your question, I assume you are already familiar with the usage of our igx-extras directives, as for the actual sample code, you can find it [here](https://github.com/IgniteUI/igniteui-angular-samples/tree/master/projects/app-lob/src/app/grid-finjs-dock-manager).

The DockManager is a WebComponent and its detailed documentation is located under the [WebComponents site of Infragistics](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/dock-manager.html)

[Here you can find the API documentation](https://www.infragistics.com/products/ignite-ui/dock-manager/docs/typescript/latest/interfaces/igcdockmanagercomponent.html) for all methods, events and etc.

Let us know if you need further assistance.
