### ISSUE TITLE
Improve "Row drag" topics to demonstrate how to get cursor position on element

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-docfx#2788]
We should add a section to the "Row drag" topics that demonstrates how the user can get which row is below the cursor. This allows for custom implementations customers often ask about - changing the drag ghost, displaying a drop indicator, expanding a parent row, [scrolling when a row is dragged to the top/bottom of the grid](https://stackblitz.com/edit/all-your-memory-belongs-to-chrome?file=src%2Fapp%2Fgrid%2Fgrid-row-reorder-sample%2Fgrid-row-reorder.ts) etc.
We may use the following example as a guide - https://codesandbox.io/s/heuristic-nightingale-kghks?file=/src/app/tree-grid-row-reorder/
Such update should be done for:

- [ ] [Grid row drag](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-drag)
- [ ] [Tree Grid row drag](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/row-drag)
- [ ] [Hierarchical Grid row drag](https://www.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/row-drag)

Related issues:
https://github.com/IgniteUI/igniteui-angular/issues/5419
https://github.com/IgniteUI/igniteui-angular/issues/9220

**Comment by sddania** [comment]
imho, the behaviour "scrolling when a row is dragged to the top/bottom of the grid" should be implemented also for the igx-list (and if is it possible to the virtual for directive), this is very usefull
