### ISSUE TITLE
Inconcictency in sample code-snippet using onColumnInit event instead of columnInit - Grid State Persistence topic

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-docfx#2846]
The examples in the "Restoring columns" sections for the [IgxGrid](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/state-persistence#restoring-columns), [IgxTreeGrid](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/state-persistence#restoring-columns) and [IgxHierarchicalGrid](https://www.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/state-persistence#restoring-columns) in the corresponding "Grid State Persistence" topics, demonstrate using the (old name) onColumnInit event, instead of [columnInit](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridbasedirective.html#columninit).

Also links point to the API docs with the old hashtags, p. ex. https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#oncolumninit

**Comment by tishko0** [comment]
I can't find onColumnInit any longer in the samples files, this seems to have been fixed. Can you check and close

**Comment by ddaribo** [comment]
@tishko0, the link names and code-snippets are OK in the docs. However I see a difference between the API link to  'latest' (opended when clicking the links in the docs), where I see some of the old output names, such as 'onColumnInit':
https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html
and the API link to 13.0.7, whick seems up to date:
https://www.infragistics.com/products/ignite-ui-angular/docs/13.0.7/typescript/classes/IgxGridComponent.html

Please, check it out.

**Comment by zdrawku** [comment]
This was a problem with the API docs content update upon deploy. Now both latest and 13.0.18 (which is the latest for 13.0.x version) are with the correct output name.
