### ISSUE TITLE
Svg icon sample does not include httpClientModule on an app level

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-docfx#2954]
Svg icon sample does not include httpClientModule on an app-level which causes an error

1. Open [svg icon](https://www.infragistics.com/products/ignite-ui-angular/angular/components/icon#svg-icons) topic and run the stackblitz sample

**Comment by Volen99** [comment]
Solved by -> https://github.com/IgniteUI/igniteui-angular-samples/pull/3054
