### ISSUE TITLE
Remove excessive blank space in grid topics

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-docfx#296]
![space](https://user-images.githubusercontent.com/14248932/38927563-d552907a-430e-11e8-91ba-90717ddd360e.PNG)

**Comment by mpavlinov** [comment]
@hanastasov "Grid Virtualization Demo" is fixed already.

**Comment by zdrawku** [comment]
@hanastasov I just reviewed the samples again. Only Virtualization sample and Selection sample left with such blank space
https://staging.infragistics.local/products/ignite-ui-angular/angular/components/grid_summaries.html
https://staging.infragistics.local/products/ignite-ui-angular/angular/components/grid_selection.html
