### ISSUE TITLE
Broken link in Advanced Filtering topic

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-docfx#2983]
1. Navigate to Grid > Filtering > Advanced Filtering [topic ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/advanced-filtering)
2. Scroll to External Advanced Filtering > Usage section
3. Check the "grid" property link in the first paragraph

Result: The link is broken.
Expected result: The component name in the link should be changed from "igxadvancedfilteringdialogcomponent" to "igxgridtoolbaradvancedfilteringcomponent".

**Comment by zdrawku** [comment]
Fixed on prod:
https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridtoolbaradvancedfilteringcomponent.html#grid
