### ISSUE TITLE
Unclear description of pinned API

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#30]
https://github.com/IgniteUI/igniteui-docfx/blob/master/en/components/navdrawer.md
Look at the description of the pinned property.
"Currently only support."  This makes no sense.  What does it currently support?  Is it unsupported?

**Comment by zdrawku** [comment]
Damyan changed this topic entirely, although we didn't make any change to the `pin` description property.

**Comment by damyanpetev** [comment]
Actually I changed the [source readme](https://github.com/IgniteUI/igniteui-angular/tree/master/src/navigation-drawer) and in the process of applying pretty much the same content to this topic.

**Comment by ig-ealbert** [comment]
This was fixed in the rewrite.
https://www.infragistics.com/products/ignite-ui-angular/angular/components/navdrawer.html
