### ISSUE TITLE
Input group API References IgxInputGroup Types

### ISSUE THREAD

**Issue by OrigamiPT** [IgniteUI/igniteui-docfx#3052]
When i go to the link there it gives me a 404

where to find it: https://www.infragistics.com/products/ignite-ui-angular/angular/components/input-group#api-references

link accessed https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/enums/igxinputgrouptype.html

**Comment by OrigamiPT** [comment]
Sorry to post on a resolved issue but as i go to the api references section and click on the IgxInputGroup Types i still get a 404 error

**Comment by zdrawku** [comment]
Yes, we closed that by mistake, the issue will be fixed once the following PR is merged to master
