### ISSUE TITLE
Update scrollbar styling topic

### ISSUE THREAD

**Issue by dobromirts** [IgniteUI/igniteui-docfx#3157]
Include additional information for scrollbar theme capabilities in the scrollbar styling topic https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/sass/configuration#scrollbar-styling .

Agenda:

- How to use the scrollbar-theme for custom scrollbar styling. Include the scrollbar-theme:
`@include scrollbar(scrollbar-theme());`
- Exposed theme parameters - size, thumb-background, track-background.
- Including scrollbar with theme with parameters examples
`- @include scrollbar(scrollbar-theme($size: 6px));`

**Comment by zdrawku** [comment]
That would be a benefitial topic update, [this PR](https://github.com/IgniteUI/igniteui-angular-samples/pull/2980) can be used as a reference of the actual changes
