### ISSUE TITLE
Typo in Grid description of catchError usage

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#32]
1. Go here:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html
2. Search for "catchError operator".

Actual Result:
"catchError operator which intercepts and Observable that failed"
Expected Result:
"catchError operator which intercepts an Observable that failed"

**Comment by SlavUI** [comment]
Hi @dianj could you fix this :) in this Sprint 

![capture](https://user-images.githubusercontent.com/33216749/34033321-6d242d58-e182-11e7-88d2-319547b3a244.PNG)

**Comment by ig-ealbert** [comment]
This seems to have been fixed in pull request #33.  What is the process now?  Does this get closed once the fix is published?  If so, how does the change move from the repo to staging to production?

**Comment by SlavUI** [comment]
@dianj Hi Dido i think this should be fixed on Staging and not made to a pull request :) and the pushed to production

**Comment by dianj** [comment]
It appears that the next step is to get confirmation from everyone involved since all recent updates to the staging site will apply on the live one. Once the confirmation is received ES will deploy.

**Comment by SlavUI** [comment]
Fix published on the Prod environment :)
