### ISSUE TITLE
Transparency on toast

### ISSUE THREAD

**Issue by ricardosaracino** [IgniteUI/igniteui-docfx#3204]
I have been trying to apply opacity via `rgba(0, 0, 0, 0.33)` to the custom toast theme but it's not working. Am i missing something?
```
$custom-toast: toast-theme(
  $palette: null,
  $schema: $light-schema,
  $border-radius: 0.625rem,
  $background: $custom-toast-background-color,
  $text-color: $custom-toast-text-color,
);
```

![image](https://user-images.githubusercontent.com/759253/169622554-8faf1d00-ae51-4cd3-949c-31fab2fe066a.png)

**Comment by ricardosaracino** [comment]
appreciate the reply, this is the effect i was looking for 

![image](https://user-images.githubusercontent.com/759253/189894599-84410f81-d355-4747-8c70-330fa10d23aa.png)

**Comment by georgianastasov** [comment]
Hi @ricardosaracino 

I am glad that you find my suggestion helpful.

Thank you for using Infragistics components.
