### ISSUE TITLE
Add customization section to Grid Cell Editing topic for excel like editing in grid

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-docfx#3219]
Add section and a sample to demonstrate how to customize the igx-grid and its editing to have excel like editing

**Comment by brianlagunas** [comment]
Let's make sure we include the enter key behavior as well. In Excel typing any character immediately edits the value of the cell and pressing enter will then commit the value and go to the cell below it without entering edit mode. Also, the enter key will navigate to the cell below (not entering edit mode) when not editing the cells.
