### ISSUE TITLE
Update the licensing topic to use the new way of importing the themes

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-docfx#3247]
https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/ignite-ui-licensing

this is in need of update around theming

**Comment by damyanpetev** [comment]
The docs guide using the use of `@import` still which is now discouraged and should instead use `@use` (🙃).
Also from this [Discord discussion ](https://discord.com/channels/836634487483269200/836636712292581456/992364011632992347) I'm getting the impression that while imports without `~` correctly map through `stylePreprocessorOptions.includePaths`, uses do not and we should check if that's the case.

PS: Oddly, [`includePaths`](https://sass-lang.com/documentation/js-api/interfaces/LegacyFileOptions#includePaths) does say it overrides [`loadPaths`](https://sass-lang.com/documentation/js-api/interfaces/Options#loadPaths) (which should affect both rules). There's also the part where `includePaths` is under a legacy options interface and we should probably switch that as well

**Comment by simeonoff** [comment]
> The docs guide using the use of `@import` still which is now discouraged and should instead use `@use` (🙃). Additionally, from this [Discord discussion ](https://discord.com/channels/836634487483269200/836636712292581456/992364011632992347) I'm getting the impression that while imports without `~` correctly map through `stylePreprocessorOptions.includePaths`, uses do not and we should check if that's the case.
> 
> PS: Oddly, [`includePaths`](https://sass-lang.com/documentation/js-api/interfaces/LegacyFileOptions#includePaths) does say it overrides [`loadPaths`](https://sass-lang.com/documentation/js-api/interfaces/Options#loadPaths) that should affect both rules. There's also the part where `includePaths` is under a legacy options interface and we should probably switch that as well

`loadPaths` isn't a valid option in angular.json's ``stylePreprocessorOptions` options.

The modifications in this tutorial work with the angular.json configuration mentioned in the article.
