### ISSUE TITLE
DV Topics are not loading code-viewer files

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-docfx#3263]
All [DV topics](https://www.infragistics.com/products/ignite-ui-angular/angular/components/bullet-graph) are not loading code-viewer files because igniteui-docfx-template is transforming path:

`iframe-src="{environment:dvDemosBaseUrl}/gauges/bullet-graph-animation"`
to:
`https://www.infragistics.com/angular-demos-dv/assets/samples/gauges--bullet-graph-animation.json`
instead of:
`https://www.infragistics.com/angular-demos-dv/assets/code-viewer/bullet-graph-animation.json`

Note that WC/React/Blazor samples use /code-viewer/ as path to JSON file and the igniteui-docfx-template transforms this path incorrectly only in Angular docs.  

@zdrawku can you fix this in igniteui-docfx-template or should the Angular DV sample browser generate .json files in /assets/samples/ instead of /assets/code-viewe/ folder?

**Comment by HUSSAR-mtrela** [comment]
@pamelabrasil and @zdrawku how should we fix this issue?

**Comment by zdrawku** [comment]
I am adding this as part of this sprint, let us get back to you

**Comment by hanastasov** [comment]
@HUSSAR-mtrela should be working on prod now.
