### ISSUE TITLE
Add a "Download Now" button to docs page

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-docfx#3276]
Add a "Download Now" button to Ignite UI for Angular [docs page](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/angular-grid-overview-guide)

Example:

![image](https://user-images.githubusercontent.com/52001020/184125648-86ea88a2-da89-4c98-9319-576de4b9ece1.png)

https://www.infragistics.com/products/ignite-ui

**Comment by zdrawku** [comment]
For the time being we've decided to make this "hello bar" static, not with a slide-down animation.

**Comment by aatanasov2** [comment]
Hi @hanastasov  @zdrawku the copy for the new hello bars in the document 

https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EWflUTJ3WvpPiBiSG5B3yOABXsmE_utbMiNeTDPbHkxuqg?e=Wjlnvt

**Comment by hanastasov** [comment]
On Staging for Angular. two bars are shown:

![image](https://user-images.githubusercontent.com/14248932/189114551-6cab7dab-e4d1-406f-9f2d-58fee0dfae57.png)

**Comment by hanastasov** [comment]
Button text appears bigger than on prod:

![image](https://user-images.githubusercontent.com/14248932/189337213-3d5e4c31-d433-427d-92a2-068bad12b12f.png)
