### ISSUE TITLE
Refactor licensing topic GitHub Actions Configuration

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-docfx#3297]
In order to prevent confusion and errors, probably we could modify the[ GitHub Actions Configuration](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/ignite-ui-licensing#github-actions-configuration) scripts like follows:
`- run: echo "@infragistics:registry=https://packages.infragistics.com/npm/js-licensed/" >> ~/.npmrc`
 `- run: echo "//packages.infragistics.com/npm/js-licensed/:_auth=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc`
  `- run: echo "//packages.infragistics.com/npm/js-licensed/:always-auth=true" >> ~/.npmrc`

**Comment by pmoleri** [comment]
Came looking for this. Current doc is wrong/incomplete. It should be updated like it's explained here.

**Comment by zdrawku** [comment]
I should have specified that log time ago, thank you for pointing it out.
It came from the angular samples ci build definitions, hence the variables:

![image](https://user-images.githubusercontent.com/11193764/193030168-cbd4b600-f3ab-4e4b-b841-6765dce9271a.png)
