### ISSUE TITLE
Add three new topics under blazor project

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx#3298]
These are the new topics:

[ How To Customize Marker Display in Blazor Charts -final COPY.docx](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EZw91-gKRuBJlmDTlGeis-EBIs2WUA0US5NOJ71fDvwKYQ?e=bQtu7p)

[ Blazor Excel Library - Disabling Automatic Formula Calculation - final COPY.docx](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/EVs_KhW-TSZDh9gZVN9J8IUBr0mO0l-CTXwP_7CVq9q7cA?e=EbtIyR)

[ Blazor WebAssembly How To Read & Write Excel Files (JP to ENG).docx](https://infragisticsinc297.sharepoint.com/:w:/g/Groups/marketing/ESImsGJPutRKoTLc06Kz63wBe7uXVvPTsU6sq6lYOXIYwg?e=wMqRfZ)

The challenge here would be to add them by ourself instead of asking X# team to do so.

**Comment by hanastasov** [comment]
Le'ts add a new HOW TO section and put the new topics there.
