### ISSUE TITLE
Update Sizing grid topic based on column width=auto

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx#3313]
This is the topic:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/sizing#default

Update it based on the ability to auto-size columns to the size of their cells and header content on initialization by setting width auto:

<column width='auto' ...>

**Comment by dkamburov** [comment]
@IMinchev64 please check that one, if it's resolved on prod or staging and close it if so
