### ISSUE TITLE
Angular Grid examples to consider for your next project (Blog article)

### ISSUE THREAD

**Issue by aatanasov2** [IgniteUI/igniteui-docfx#3322]
Marketing is working on a new blog article targeting angular grid keywords. This is planned for an external publisher ( Medium/Dzone), or we can publish it on the Infragistics blog.

Marketing to provide draft copy first week of October. We need a technical review/examples. 

Proposed structure: 

https://infragisticsinc297.sharepoint.com/:w:/r/Groups/marketing/_layouts/15/Doc.aspx?sourcedoc=%7B85d3e31e-12b2-4e47-8670-e57551d0302d%7D

Keywords:

Angular grid: https://infragisticsinc297.sharepoint.com/:x:/r/Groups/marketing/_layouts/15/Doc.aspx?sourcedoc=%7Bcb2da3cc-5115-46dc-96b7-92c3658385a7%7D

Angular tree grid https://infragisticsinc297.sharepoint.com/:x:/r/Groups/marketing/_layouts/15/Doc.aspx?sourcedoc=%7B033ad285-cb4c-4fe3-8c2e-3b0bc04b285c%7D

Angular hierarchical grid: 

https://infragisticsinc297.sharepoint.com/:x:/r/Groups/marketing/_layouts/15/Doc.aspx?sourcedoc=%7Bf66a15f4-4032-400e-866e-34fe036c4059%7D

Target publish date 14/10/2022

Slingshot task: https://my.slingshotapp.io/openTask/e97e10ef_4128af37-0381-486b-de93-3aa9a251eb08

**Comment by aatanasov2** [comment]
@hanastasov  draft copy is ready for review
https://infragisticsinc297.sharepoint.com/:w:/r/Groups/marketing/_layouts/15/Doc.aspx?sourcedoc=%7B578f113f-5f69-4115-8600-d4410687bb58%7D

**Comment by zdrawku** [comment]
I've added my comments.
