### ISSUE TITLE
Increasing Performance of Angular Applications: How to use change detection and component reusing to increase app efficiency REVIEW

### ISSUE THREAD

**Issue by aatanasov2** [IgniteUI/igniteui-docfx#3350]
We had a request from an external publisher to write an article on Angular Change Detection. 

 Directed to an audience of software developers. 

https://sdtimes.com/

This is similar to the article we published on our blog back in April:

https://www.infragistics.com/community/blogs/b/infragistics/posts/what-is-angular-change-detection

We need a review of the draft copy below:

https://infragisticsinc297.sharepoint.com/:w:/r/Groups/marketing/_layouts/15/Doc.aspx?sourcedoc=%7B6e92cd2b-e752-44d5-ac5c-b7fceed36ace%7D

**Comment by hanastasov** [comment]
The draft is reviewed, edits left in blue.
