### ISSUE TITLE
5 Angular data grid features you never knew you need REVIEW 

### ISSUE THREAD

**Issue by aatanasov2** [IgniteUI/igniteui-docfx#3377]
Review content and create gifs that best describe the features.

https://infragisticsinc297.sharepoint.com/:w:/r/Groups/marketing/_layouts/15/Doc.aspx?sourcedoc=%7B422cf692-cdc8-4fea-bfd8-bcb62c97845e%7D

**Comment by zdrawku** [comment]
That is completed and available here https://www.infragistics.com/community/blogs/b/infragistics/posts/top-5-angular-data-grid-features
