### ISSUE TITLE
Category Chart - Explore Chart Types topic issues

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-docfx#340]
goto: https://staging.infragistics.local/products/ignite-ui-angular/angular/components/categorychart_explore_chart_types.html

1) topic is mis-titled
this topic is titled explore chart types but is actually about axes. This should renamed in the navigation bar and in the topic.

Also the name of the demo should be changed.

2) strange line in axis titles section
scroll to axis titles section, there is a line under the second paragraph "title on the x-axis and y-axis" which spans to the right side of the page.

3) in Axis Interval it should say "axis interval" instead of "axis major interval" since that is property name used to control the major interval. Also it should mention that this also affects tickmarks: major gridlines, tickmarks, and axis labels"

**Comment by HUSSAR-mtrela** [comment]
@IGvaleries  item# is on Jason's request!

**Comment by HUSSAR-mtrela** [comment]
@IGvaleries item# 2 is expected because this his how section headers are separated
