### ISSUE TITLE
Child topics are not loaded when using the NEW tag for parent topics

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx#344]
In the toc.yml if NEW tag is added, subtopics are not loaded:

Example:
- name: Category Chart
  href: categorychart.md
  new: true
  items:
    - name: Explore Chart Types
      href: categorychart_explore_chart_types.md
      new: true

Image:

![image](https://user-images.githubusercontent.com/11193764/39109393-6e910fae-46d5-11e8-9b95-32916a640b2b.png)

Note: 

I have tried to add it in different positions, although it didn't worked. Review the changes from Simeon, maybe some additional changes should be implemented:
https://github.com/IgniteUI/igniteui-docfx/pull/326/files

For a temporary solution, new tags have been set to all subtopics.

**Comment by tiliev** [comment]
@zdrawku, please share which parent menu items should be marked with new so we could add them as a part of the fix.

**Comment by zdrawku** [comment]
Parent topics that should be marked with NEW tag:

Grid
Category Chart
Financial Chart
