### ISSUE TITLE
Confusing description for scrollbar visibleItemsCount

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#35]
1. Go here:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/scrollbar.html
2. Observe the description for visibleItemsCount in the API table.

Actual result:
The total amount of items in that will be virtualized.

Expected result:
I don't know.  Something like "The total number of items that are visible."  I assume that's what it actually does based on the name, but I don't know if the implementation matches the name.

Is it possible that the descriptions for the `totalItemsCount` and `visibleItemsCount` inputs are switched?  If so, I would recommend something like "The total number of items in the items source" and "The total number of visible items".

**Comment by zdrawku** [comment]
This doc and the whole scroll component will be removed entirely.
We are going to use the virtual for directive:
https://staging.infragistics.local/products/ignite-ui-angular/angular/components/for_of.html
