### ISSUE TITLE
Add upgrade guide for the input changes in 15.1

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-docfx#3564]
The upgrade guide should describe the new sizes and tell users that they can control the size through display density.

IT should also provide a workaround using styles to the arrow background being visible now.

**Comment by desig9stein** [comment]
@ChronosSF The display density is not a new functionality of the input, maybe we should add an example inside the input topic that explains how to set display density on the input.
 
The arrow background is not part of the input theme it is part of the select and combo themes, There are exposed properties that allow the user to change the background and the icon color. We have styling samples for those components that can show this.

**Comment by ChronosSF** [comment]
It's not about making it seem like new functionality. The idea is to notify the customers the sizes are changed and remind them they can control them using display density. Something like this:

> In 15.1 the sizes of the input components when using Material themes has increased to match Material spec. If your application is negatevily affected by the change, you can use the `displayDensity` input and set it to a more dense setting, e.g. from `comfortable` to `cozy` or from `cozy` to `compact`
