### ISSUE TITLE
Grid remote virtualization demo doesn't show data

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#357]
Go here:
https://staging.infragistics.local/angularsite/components/grid_virtualization.html
Observe the demo under "Grid Remote Virtualization Demo".
There is no data.

**Comment by zdrawku** [comment]
It seems that the Ajax request to get the remote data is suppressed. @mpavlinov commented about this in [PR](https://github.com/IgniteUI/igniteui-angular-samples/pull/171), although I am not sure if the issue is the same.

**Comment by mpavlinov** [comment]
@ig-ealbert @zdrawku: This is fixed in https://github.com/IgniteUI/igniteui-angular-samples/pull/267

**Comment by ig-ealbert** [comment]
Verified on staging.
