### ISSUE TITLE
Confusing description for slider value

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#36]
1. Go here:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/slider.html
2. Check the description for `value`.

Actual result:
By default if no value is set the default value is same as lower upper bound.

Expected result:
I don't know.  What is the default value?  Is it the lower bound, the upper bound, or some average?  I assume this is simply one number, not two?

**Comment by ig-ealbert** [comment]
This was addressed in the rewrite.  Can be closed when this is published.

**Comment by zdrawku** [comment]
Fixed: https://staging.infragistics.local/products/ignite-ui-angular/angular/components/slider.html
