### ISSUE TITLE
The grid editing topic has malformed metadata section that appears in the doc

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-docfx#3641]
Run and open the grid editing topic, or check it on staging: https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/editing

Metadata section shows as text on top:

![image](https://github.com/IgniteUI/igniteui-docfx/assets/10397980/c878c773-f6ee-49c2-9ffb-c911bd3bd3e9)

**Comment by dobromirts** [comment]
Not reproducible anymore on staging and prod.
