### ISSUE TITLE
API links using base directive do not work

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-docfx#3653]
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell-selection#clear-cell-selection click on the API link for the method. It points to 
https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridbasedirective.html#clearCellSelection
which doesn't exist (404)

This worked up until 15.1 https://www.infragistics.com/products/ignite-ui-angular/docs/15.1.8/typescript/classes/IgxGridBaseDirective.html#clearCellSelection 

I believe this is affected by a 16.0 change @kdinev made to skip the base directive from the public API exports, which I suppose in turn removed it from typedoc output. So links like this one:
https://github.com/IgniteUI/igniteui-docfx/blob/a557e6d8b14ba442bbf1f2e3fa37a66d109c0375/en/components/grids_templates/cell-selection.md?plain=1#L151
Need to be updated to use their respective Grid components's API page, e.g. https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxGridComponent.html#clearCellSelection

**Comment by hanastasov** [comment]
All links are fixed.
