### ISSUE TITLE
Right TOC is broken with latest Edge Dev browser

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx#3665]
[Open Edge Dev](https://www.microsoft.com/en-gb/edge/download?form=MA13FJ)
Open the Grid main topic.
Look at the right TOC:
![image](https://github.com/IgniteUI/igniteui-docfx/assets/11193764/e4c65514-a8b1-4125-96e7-7bc9244e9382)

**Comment by hanastasov** [comment]
I cant reproduce it with 

Microsoft Edge
Version 116.0.1908.0 (Official build) dev (64-bit)
