### ISSUE TITLE
Category Chart Types table is difficult to read

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#369]
https://staging.infragistics.local/angularsite/components/categorychart.html
Observe the table.
The description is smushed together.
It's even worse here:
https://jp.staging.infragistics.local/angularsite/components/categorychart.html
I can think of 3 options to fix it:
1. Remove the images as was done in financial chart.
2. Somehow set a width on the column?
3. Resize the images to be much smaller.

**Comment by zdrawku** [comment]
No longer applicable
