### ISSUE TITLE
Slider type has the wrong description

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#38]
1. Go here:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/slider.html
2. Check the `type` API description.

Actual result:
The duration visibility of thumbs labels. The default value is 750 milliseconds.

Expected result:
The type of the slider?  Give some more information here?

**Comment by ig-ealbert** [comment]
This was addressed in the topic rewrite.  This can be closed when it is published.

**Comment by zdrawku** [comment]
Fixed: https://staging.infragistics.local/products/ignite-ui-angular/angular/components/slider.html
