### ISSUE TITLE
StackBlitz buttons does not work if clicked before the page loads

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-docfx#407]
Sometimes StackBlitz buttons does not work if clicked when the page is not entirely loaded. Reproducible with slow bandwidth.
Please disable the buttons while the content is loading and enable them when they are clickable.

**Comment by tiliev** [comment]
[This ](https://github.com/IgniteUI/igniteui-docfx/issues/183) enhancement was implemented to help complete this feature. This issue should be moved to https://github.com/IgniteUI/igniteui-docfx-template. The change should be implemented in this [file](https://github.com/IgniteUI/igniteui-docfx-template/blob/master/styles/stackblitz-handler.js).

**Comment by hanastasov** [comment]
Moved to `[this issue](https://github.com/IgniteUI/igniteui-docfx-template/issues/36)`.
