### ISSUE TITLE
Some samples have their vertical scrollbar flickering

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-docfx#418]
### Description  
The following samples have their vertical scrollbar flickering - like seen for a moment and then it disappears:

Grid Filtering
Grid Searching
Financial Chart
Financial Real Time Data
Financial High Volume Data
Performance
Binding to multiple data sources
Panes
Custom Indicators
Custom tooltips

### Result  
Open any of the above and notice how the scrollbar is there for a moment

### Expected result  
No scrollbars to be seen.

**Comment by zdrawku** [comment]
Closing this issue, we are going to follow entirely different approach
