### ISSUE TITLE
Backslashes visible in types

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#42]
https://www.infragistics.com/products/ignite-ui-angular/angular/components/calendar.html
In the table, some of the types have backslashes in them.  Is that correct?
Ex. `Number \| WEEKDAYS`
Is the intention that it's "Number or WEEKDAYS"?  In that case, remove the `\` because it's already escaped in the backticks.
```
Date \| Date[]
date: Date \| Date[]
```

**Comment by zdrawku** [comment]
We are currently updating the Calendar topic: Telated to #131
