### ISSUE TITLE
Add anchor elements to the Headers

### ISSUE THREAD

**Issue by pamelabrasil** [IgniteUI/igniteui-docfx#437]
Add a link for the header in the table of content to a topic?
 
For example, add an overview page when the end user clicks on the headers – “Grids & Lists” and “Charts”.

**Comment by zdrawku** [comment]
Hey Pamela,
I wanted to clarify the requirement, you want to have a clickable category header that will generate a link, like it is in our Ignite UI for JavaScript help topics?

https://www.igniteui.com/help/data-source-components

One thing that we can do is to add such .md file that will lists all child topics, as it is in the example above.

As we spoke with @tiliev this could be achieved. Lets hear some UX opinion though, @StefanIvanov @simeonoff what do you think?

**Comment by pamelabrasil** [comment]
yes, the headers in Angular need to be clickable so that there is content that can be added. For example Grids & Lists would need to link to a topic (GridListsOverview.md). It wouldn't list all the child topics. Marketing team are working on a landing page which would contain descriptions / screenshots of all the features for each control.

**Comment by pamelabrasil** [comment]
Also to add, this landing page content is planned to be released for the next Angular release, which I believe is at the end of this month (June).

**Comment by simeonoff** [comment]
@pamelabrasil The requested feature is on pull request here https://github.com/IgniteUI/igniteui-docfx-template/pull/11

**Comment by zdrawku** [comment]
Today we are going to verify it, thank you @simeonoff

**Comment by zdrawku** [comment]
Closing this issue, this functionallity has been added with PR https://github.com/IgniteUI/igniteui-docfx-template/pull/11
