### ISSUE TITLE
Add '+' symbol to parent nodes

### ISSUE THREAD

**Issue by pamelabrasil** [IgniteUI/igniteui-docfx#440]
For parent nodes, add '+' symbol to let the end user know that node can be expanded to view the children nodes. 
For example, look at the following table of contents for reference
https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html

**Comment by simeonoff** [comment]
@pamelabrasil Could you please log this issue under the [**template**](https://github.com/IgniteUI/igniteui-docfx-template) repository?
