### ISSUE TITLE
Column moving output is missing type

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#474]
https://jp.staging.infragistics.local/angularsite/components/grid_column_moving.html#%E5%87%BA%E5%8A%9B
The first row has no type, so the description appears in the type column.  The type should be EventEmitter, like here: https://staging.infragistics.local/angularsite/components/grid_column_moving.html#outputs

**Comment by yoshimis** [comment]
Fixed: https://github.com/IgniteUI/igniteui-docfx/pull/477.

**Comment by ig-ealbert** [comment]
Verified.
