### ISSUE TITLE
Two new grid topics are not localized

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#475]
https://jp.staging.infragistics.local/angularsite/components/grid_editing.html
https://jp.staging.infragistics.local/angularsite/components/grid_multi_column_headers.html
These two new topics should be localized and the TOC should be updated.

**Comment by yoshimis** [comment]
https://github.com/IgniteUI/igniteui-docfx/pull/488

**Comment by ig-ealbert** [comment]
Verified.  Created #508.
