### ISSUE TITLE
Update all document with the new repository name

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-docfx#48]
The JS Blocks repository has now been renamed according to our blog post:
https://www.infragistics.com/community/blogs/b/infragistics/posts/ignite-ui-github-repo-name-changes

All references to `igniteui-js-blocks` should be replaced with `igniteui-angular`

**Comment by simeonoff** [comment]
Resolved with https://github.com/IgniteUI/igniteui-docfx/pull/53
Closed #53
