### ISSUE TITLE
bs-docs-sidebar - View zoom/resize issue

### ISSUE THREAD

**Issue by sbozalieva** [IgniteUI/igniteui-docfx#50]
### bs-docs-sidebar - View zoom/resize issue

If the browser view is or has been zoomed in/out, the sidebar shows the previous item as selected instead of the actual selected one.  

Discussed the same issues with resizing the browser view, however currently I cannot reproduce them.

### Expected result

Sidebar will highlight as active the selected item, not the previous one.

### Attachments 
![screen shot 2018-01-16 at 17 38 40](https://user-images.githubusercontent.com/23053821/34999381-3a6d09b2-faea-11e7-9949-1a4932ea82fa.png)

**Comment by zdrawku** [comment]
@sboykova I cannot reproduce this issue, could you please provie more detailed steps to reproduce?

**Comment by simeonoff** [comment]
Closing this as it's related to another project.

**Comment by hanastasov** [comment]
Cannot reproduce the issue as well.
