### ISSUE TITLE
Document displayDensity option

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx#556]
Add a description for displayDensity option and everything related to it.

Example:
Columns have a minimum allowed column width. Depending on the displayDensity option, they are as follows: 
"compact": 24px 
"cosy": 32px 
"comfortable ": 48px

**Comment by kdinev** [comment]
I'm pretty certain in "comfortable" mode, for example, that the min-width is 48px. This is not the only thing the `displayDensity` affect, however. Padding and margin changes, as well as general display difference and use-cases should be documented.

**Comment by zdrawku** [comment]
Also we should mention that curently these sized cannot be changed by the end used and that Grid's density option is [Material Design Density](https://material.io/design/layout/density.html#typographic-density) based
