### ISSUE TITLE
Update the documentation related to disabled property renaming

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-docfx#558]
We have made a change where we are updating all properties which are connected to disabled mode due consistency between the components.
The following components should be updated:

- [x] date-picker
- [x] input directive
- [x] input-group
- [x] dropdown-item
- [x] bottom-navigation
- [x] tabs
- [x] time-picker

Refer the [pull request](https://github.com/IgniteUI/igniteui-angular/pull/1357) which makes the following update.

**Comment by Lipata** [comment]
Drop down item disabled is not exposed in the drop down topic.
