### ISSUE TITLE
an overlay main page's file name is different naming from other components.

### ISSUE THREAD

**Issue by DaizenIG** [IgniteUI/igniteui-docfx#560]
Overlay's sample page is named different from other components' main pages: 

Actual result:
Overlay: [componentname]_main.md
https://github.com/IgniteUI/igniteui-docfx/blob/master/en/components/overlay_main.md

Expected resukt:
all other components main pages are named this way.
[cmponentname].md
e.g. https://github.com/IgniteUI/igniteui-docfx/blob/master/en/components/ripple.md

this affects both en and jp. If the file is not intended to name the way, please align overlay's filename.

**Comment by zdrawku** [comment]
This issue should be logged in the [docfx](https://github.com/IgniteUI/igniteui-docfx) repo
