### ISSUE TITLE
Internationalize header and footer

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/igniteui-docfx#62]
In order to release the Angular documentation for 18.1, we need the header and footer of the site to be internationalized.

The website header and footer seem to be hardcoded instead of being pulled from the staging or live sites.  What was the rationale behind this decision?
https://github.com/IgniteUI/igniteui-docfx/tree/d3f6f66825ddf3d266be4b195dce965b0fb90868/templates/ignite-ui-template/partials

If possible, can the header and footer pull content from the live or staging websites so that we don't duplicate content as hardcoded files?  This is how it's done in the Ignite UI for JavaScript samples.

**Comment by kdinev** [comment]
Reopening since this is not done.

**Comment by kdinev** [comment]
Closing again. I checked and the partials with hardcoded strings are not used.

**Comment by zdrawku** [comment]
Reopen the issue, related to #21

**Comment by tiliev** [comment]
@ig-ealbert, could you apply the localization of the second header to this file - https://github.com/IgniteUI/igniteui-docfx/blob/master/jp/toc.yml?

**Comment by ig-ealbert** [comment]
@tiliev I have submitted a pull request to address this issue.  Thank you for showing me where this subheader content exists.
