### ISSUE TITLE
Topic with more than one iframe in it causes BrowserSync to reload the page

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-docfx#672]
**Steps to reproduce:**
1. Run the `igniteui-angular-samples` application.
2. Open `igniteui-docfx` project
3. `npm install`
4. `npm start`
5. Go on a topic with more than one iframes in it.

**Result:**
The browser load the page and then reloads it.

**Expected:**
The browser should load the page only once.

_I think the browserSync reloads the page. The package was updated recently._

**Comment by kdinev** [comment]
@tiliev I updated the package with `npm audit`. You can downgrade it if there's an issue!

**Comment by tiliev** [comment]
After further investigation, I cannot find other reason except the slowly loading iframes. I logged the issue in the `browserSync` repository - https://github.com/BrowserSync/browser-sync/issues/1604.
The current workaround for this issue is to downgrade locally the `browser-sync` package version:
`npm i browser-sync@2.18.13`.
We'll wait for response before downgrading.
