### ISSUE TITLE
[Grid Editing] Demo is broken

### ISSUE THREAD

**Issue by pnishimura** [IgniteUI/igniteui-docfx#703]
Hi guys,

Today I just found that the demo of "Grid Editing" is broken.

https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_editing.html

![image](https://user-images.githubusercontent.com/29943424/46132863-307b8480-c27a-11e8-9691-ed4e73f9db43.png)

I also found that the demo in StackBlitz is broken as well.

https://stackblitz.com/angular/vmlaoqmexev

![image](https://user-images.githubusercontent.com/29943424/46133138-c4e5e700-c27a-11e8-8864-b6fe7039a994.png)

As far as I investigated,
IgxComboModule is not found in app.module.ts.

![image](https://user-images.githubusercontent.com/29943424/46133219-ed6de100-c27a-11e8-8227-fd4ba7ca6864.png)

This issue is also found in JP website.
https://jp.infragistics.com/products/ignite-ui-angular/angular/components/grid_editing.html

It would be great if you guys can fix it.

Thanks,
Paul

**Comment by mtsvyatkova** [comment]
@pnishimura 

It seems that the behavior is not reproducible anymore and the sample is loaded in StackBlitz so I am closing this issue.
