### ISSUE TITLE
StackBlitz samples do not work in IE 11

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-docfx#722]
Steps to reproduce:
1. Open any StackBlitz sample in IE 11.

Result:
Errors in the console:
![ig-ng-stackblitz-errors-ie11](https://user-images.githubusercontent.com/6439482/46272222-bc323100-c558-11e8-9d18-ba5c776db5ad.PNG)

Expected:
The sample should run.

**Comment by tiliev** [comment]
The issue is logged in the SB repo - https://github.com/stackblitz/core/issues/706.

**Comment by tiliev** [comment]
StackBlitz team fixed this and it is working.

**Comment by taranjs** [comment]
Still happens for me. Apologies if I should have logged a new issue instead. Please see attached screenshot.

![image](https://user-images.githubusercontent.com/7659814/55547514-5ff7c780-56c9-11e9-92af-4b4af40610fe.png)

**Comment by zdrawku** [comment]
@taranjs  Could you please share the sample with us as well?
