### ISSUE TITLE
Broken project with DocFX version 2.39.2.0

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-docfx#735]
### Steps to reproduce:
1. `choco install docfx --version 2.39.2.0` - this is currently the latest version.
2. `npm i`
3. `npm start`

### Result:

![immutable-error](https://user-images.githubusercontent.com/6439482/46605990-f88b0180-cb03-11e8-8513-5ee2abfb73e0.PNG)

The reason seems to be our environment plugin uses an older DocFX version (2.28.3): - https://github.com/IgniteUI/igniteui-docfx-template/blob/master/post-processors/PostProcessors/packages.config#L4. Please keep in mind updating the plugin version would require updating the docfx version on all of our servers.

Further investigation is required.

### Workaround
Please run `choco install docfx --version 2.26.4.0 --force` for a working project.

**Comment by tiliev** [comment]
These are steps required to update the package (in theory):
 - Update the docfx to the latest version locally using the command from above
 - Open the **Post Processors** [project ](https://github.com/IgniteUI/igniteui-docfx-template/tree/master/post-processors) from the `igniteui-docfx-template` repository. Update the `Microsoft.DocAsCode.Plugins` package to the corresponding docfx version. Build the project. The newly built DLL should be committed. Do not update other packages if it is not needed. [Here](https://dotnet.github.io/docfx/tutorial/howto_add_a_customized_post_processor.html) you can see that the other needed packages are up-to-date.
 - On this step you should be able to run and test the docs correctly.
- If everything is OK, you should notify the developers from the Ignite UI for Angular team to update their versions to latest. 
 - When you deploy the docs with the new version, you should notify the DevOps to update the DocFX versions on each environment.

**Comment by zdrawku** [comment]
This is something that will require more advanced testing

**Comment by zdrawku** [comment]
Done, use docfx-template [version 2.3.0](https://github.com/IgniteUI/igniteui-docfx-template/releases/tag/2.3.0)
