### ISSUE TITLE
Create CLI Commands section

### ISSUE THREAD

**Issue by bazal4o** [IgniteUI/igniteui-docfx#755]
We need to add CLI Commands section which lists all the supported commands by the CLI.
Those should be similar to github wiki pages: https://github.com/IgniteUI/igniteui-cli/wiki

**Comment by zdrawku** [comment]
This is now covered by the following Ignite UI CLI topics:
[Getting started](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/cli-overview.html) and [Step by step guide](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/cli/step-by-step-guide.html)
