### ISSUE TITLE
Doughnut chart and pie chart StackBlitz samples do not work

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-docfx#789]
## Steps to reproduce
1. Open https://staging.infragistics.local/products/ignite-ui-angular/angular/components/doughnutchart.html or https://staging.infragistics.local/products/ignite-ui-angular/angular/components/piechart.html
2. Click any of the StackBlitz buttons

## Result
StackBlitz samples do not open.

## Expected result
Stackblitz samples should open.

**Comment by zdrawku** [comment]
These samples were moved and fixed later on
