### ISSUE TITLE
Broken link for nav drawer API reference

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-docfx#822]
The link for nav drawer API reference is broken
[Broken link](https://www.infragistics.com/products/ignite-ui-angular/angular/components/%7Benvironment:angularApiUrl/classes/igxnavigationdrawercomponent.html)

**Comment by zdrawku** [comment]
The only broken link that I see here is the module reference:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/navdrawer.html

![image](https://user-images.githubusercontent.com/11193764/56289018-a36e1f00-6128-11e9-8852-e66ef197d167.png)

**Comment by zdrawku** [comment]
Fixed
