### ISSUE TITLE
Table on Known Limitations is broken in JP doc

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-docfx#832]
In JP doc, the table is broken. In EN doc, the table is configured correctly.

https://jp.infragistics.com/products/ignite-ui-angular/angular/components/grid_search.html#%E6%97%A2%E7%9F%A5%E3%81%AE%E5%95%8F%E9%A1%8C%E3%81%A8%E5%88%B6%E9%99%90

JP
![image](https://user-images.githubusercontent.com/14340675/48336326-5ed6e700-e6a3-11e8-8a5d-e1ca945a9835.png)

EN
![image](https://user-images.githubusercontent.com/14340675/48336362-744c1100-e6a3-11e8-904c-0b7ec3536707.png)

**Comment by ymita** [comment]
The "searchable" property is missing on the JP doc. Please see the screenshot below.
![image](https://user-images.githubusercontent.com/14340675/48470536-0cc5cb00-e835-11e8-8704-deb2cce75d0d.png)

**Comment by zdrawku** [comment]
resolved
