### ISSUE TITLE
"Ignite UI for Angular Themes" link points to staging saas site.

### ISSUE THREAD

**Issue by yoshimis** [IgniteUI/igniteui-docfx#836]
1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/theming-demo.html
2. Click "Ignite UI for Angular Themes" link under Theme Setting.

It opens: https://staging.infragistics.local/products/ignite-ui-angular/docs/sass/

**Comment by HristoP96** [comment]
Hi Yoshimi, 

This bug is fixed in this PR #846.

When the changes are applied in production this bug will not be reproducible.

**Comment by simeonoff** [comment]
@HristoP96 thanks!
