### ISSUE TITLE
Review and fix all hardcoded environment references

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-docfx#843]
Some references were missed in this [PR](https://github.com/IgniteUI/igniteui-docfx/pull/706
), we should fix them

**Comment by HristoP96** [comment]
Found wrong links in topics:

- [ ] Grid Selection
- [ ] Grid Display Density
- [ ] Theming Demo
- [ ] Toggle Directive

and in their JP and KR versions respectfully.
