### ISSUE TITLE
Embedded samples on-demand loading

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-docfx#847]
The frame loads the entire samples app and topics with multiple samples a bit to load.
It'd be a performance improvement (especially in dev mode) if the embedded sample can load on-demand as the page is scrolled through.
Not too noticeable on production and there aren't that many topics with a lot of samples, just something that can be looked into in the future.

**Comment by tiliev** [comment]
Please follow these steps for implementing lazy loading in a topic:
1. Generally the first sample should not be lazily loaded. Add `loading` class to the sample container and `onload="onSampleIframeContentLoaded(this);` on the `iframe`.
2. On all of the sample you'd like to load lazily, add
- `loading` class to the sample container
- `lazyload` class to the `iframe`
- rename the `src` of the `iframe` to `data-src`
- you shouldn't have `onload="onSampleIframeContentLoaded(this);"`

**Comment by zdrawku** [comment]
@Aleksandyr and @HristoP96 think of a way to automate this process for the current topic.
I am going to add a readme section about the lazy loading configuration for all upcoming topics

**Comment by HristoP96** [comment]
All the PRs related to this issue are merged.
