### ISSUE TITLE
Topic for "Tooltip Types" for FinancialChart and CategoryChart missing in JP version

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-docfx#851]
The topic for [**Tooltip Types**](https://staging.infragistics.local/products/ignite-ui-angular/angular/components/categorychart_tooltip_types.html) topic for Category chart is missing in JP version.

![categoryjp](https://user-images.githubusercontent.com/25771040/48785378-4a22d080-eced-11e8-8c9d-e728330a0ff7.PNG)

The topic for [**Tooltip Types**](https://staging.infragistics.local/products/ignite-ui-angular/angular/components/financialchart_tooltip_types.html) topic for Financial chart is missing in JP version.

![financialjp](https://user-images.githubusercontent.com/25771040/48785391-4bec9400-eced-11e8-9703-efc7f192ff99.PNG)

**Comment by HristoP96** [comment]
Related issue: #850

**Comment by HristoP96** [comment]
@yoshimis Could you addthe " Tooltip Types" topic in the jp [toc.yml](https://github.com/IgniteUI/igniteui-docfx/blob/master/jp/components/toc.yml) file.

**Comment by yoshimis** [comment]
@HristoP96  " Tooltip Types" topic added in the jp toc.yml file.
