### ISSUE TITLE
igxGrids are not displayed properly in the JP sample page

### ISSUE THREAD

**Issue by mkamiishi** [IgniteUI/igniteui-docfx#853]
All igxGrids in the JP sample page are not displayed properly.

Examples:
https://jp.infragistics.com/products/ignite-ui-angular/angular/components/grid_editing.html
https://jp.infragistics.com/products/ignite-ui-angular/angular/components/grid_paging.html

This problem is reproducible only with IE.
![grid_ng](https://user-images.githubusercontent.com/7463490/48819819-3df24e00-ed95-11e8-8eae-dd8593c74b4a.png)

**Comment by zdrawku** [comment]
@HristoP96 will take care of this

**Comment by HristoP96** [comment]
Related issue-
[https://github.com/IgniteUI/igniteui-angular/issues/3095](https://github.com/IgniteUI/igniteui-angular/issues/3095)

**Comment by zdrawku** [comment]
This issue is related to the `autoprefixer` fix for the grid https://github.com/IgniteUI/igniteui-angular/issues/3512
