### ISSUE TITLE
Create igxLabel, igxInput user story and update current topics based on the article guidance

### ISSUE THREAD

**Issue by bkulov** [IgniteUI/igniteui-docfx#86]
Combine igxLabel and igxInput into one topic.

Article guidance - https://github.com/IgniteUI/igniteui-docfx/blob/master/.github/CONTRIBUTING.md

**Comment by bkulov** [comment]
Closing this issue as it's a duplicate of #87.

**Comment by sstoyanovIG** [comment]
All done
