### ISSUE TITLE
Topic headers are incorrectly bold

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-docfx#868]
Topic headers are incorrectly bold

**Actual result:**
**h4** headers are **not** bold and thus are **in**distinguishable from ordinary text

**Expected result:**
**h4** headers are bold and thus distinguishable from ordinary text

![headersissue](https://user-images.githubusercontent.com/12784974/49286957-63254180-f4a4-11e8-82e9-c2a443e9b6ab.png)

**Comment by tiliev** [comment]
This is probably related to the bundling and minification I introduced a week ago. I'll take a look.
