### ISSUE TITLE
missing localization files for jp and kr for charts

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-docfx#944]
In ..\igniteui-docfx\jp\components are missing files:

- categorychart_axis_options.md
- categorychart_highlighting.md
- categorychart_tooltip_templates.md
- financialchart_tooltip_templates.md

In ..\igniteui-docfx\kr\components is missing file:

- categorychart_axis_options.md

These files exist in ..\igniteui-docfx\en\components.

**Comment by yoshimis** [comment]
I have added the missed files. Some of them were already added.

**Comment by zdrawku** [comment]
As Yoshimi said, the files are present now
