### ISSUE TITLE
Research the options for sharing content between topics. 

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-docfx#952]
Research what are the options to use the same or similar to some extent text content with different samples and code snippets, so we don't end up having the same topic content for each of the 3 grids in 3 different places.

**Comment by mtsvyatkova** [comment]
[gulp-file-insert](https://www.npmjs.com/package/gulp-file-insert) is a Gulp plug-in which allows an .md file to be inserted in the content of another .md file. This will allow us to have one base topic for, let’s say, sorting of the grids, and modify it for each grid – IgxDataGrid, IgxTreeGrid, IgxHierarchicalGrid by inserting specific code snippets and text content in the base topic.

**How does it work?**
The gulp-file-include should be installed first (npm install gulp-file-include) which will add "gulp-file-insert" as dependency in the package.json.

The base topic which is used as template should contain markers that are going to be replaced with the custom content. E.g.   where the API references needs to be inserted. 

Then a .md file for grid’s API references needs to be created.

The last step is to create a gulp task for each grid to replace the markers in the base topic with the appropriate content. The example below inserts three files and generates a new grid-sorting.md file inside the /tree-grid folder
```
gulp.task('fileinsert', function() {
    gulp.src(`${DOCFX_ARTICLES}/base_grids/grid-sorting.md`)
    .pipe(gfi({
        "<!-- #insert demo -->": `${DOCFX_ARTICLES}/tree-grid-docs/demo.md`,
        "<!-- #insert API references -->": `${DOCFX_ARTICLES}/tree-grid-docs/api-refs.md`,
        "<!-- #insert Additional resources -->": `${DOCFX_ARTICLES}/tree-grid-docs/additional-resources.md`
    }))
    .pipe(gulp.dest(`${DOCFX_ARTICLES}/tree-grid/`));
});
```

**Pros:**
-	Having one base topic for each feature shared between the grids.
-	Easy to maintain.
-	We already use gulp tasks which are executed during build.

**Cons:**
-	The gulp task includes the whole .md file and each piece of content which should be different for any of the grids is handled as separated .md file.
-	It does not support variables which could be used in the base .md file for customizing the text content to be displayed only for some of the grids.
