### ISSUE TITLE
The "Search API" limitation is still present in the Tree Grid documentation

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-docfx#961]
### Description  
The "Search API" limitation is still present in the Tree Grid documentation.

### Steps to reproduce  

Navigate to the following link:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid.html#known-limitations

### Result  
The "Search API" limitation is present in the **Known Limitations** table.

### Expected result  
The "Search API" limitation is **not** present in the **Known Limitations** table.

### Attachments  

![image](https://user-images.githubusercontent.com/12784974/51523899-59c9ad00-1e35-11e9-9bdf-bde8c9701290.png)

**Comment by DiyanDimitrov** [comment]
Closed by #980.
